notes/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', Posts.as_view(), name='index'),
    path('about/', views.about, name="about"),

    path('materials/', materiallistview.as_view(), name="materials"),
    path('labposts/', labpostlistview.as_view(), name="labposts"),

    path('fullpost/<int:pk>', fullpost.as_view(), name='full_post'),
    path('material/<int:pk>', filefullpost.as_view(), name='material'),

    path('newpost/', PostCreateView.as_view(), name="newpost"),
    path('materialpost/', FilePostCreateView.as_view(), name="materialpost"),


    path("notes/fullpost/<int:pk>/update",
         PostUpdateView.as_view(), name="update"),
    path("notes/material/<int:pk>/update",
         FilePostUpdateView.as_view(), name="material_update"),


    path("notes/fullpost/<int:pk>/delete",
         PostDeleteView.as_view(), name="delete"),
    path("notes/material/<int:pk>/delete",
         FilePostDeleteView.as_view(), name="material_delete"),


    path("user/<str:username>", UserPostListView.as_view(), name="user_posts"),

    path("category/sem/<int:semester>",
         SemesterLabListView.as_view(), name="semester_lab"),
    path("category/branch/<str:branch>",
         BranchLabListView.as_view(), name="branch_lab"),
    path("material/sem/<int:semester>",
         SemesterMaterialListView.as_view(), name="semester_material"),
    path("material/branch/<str:branch>",
         BranchMaterialListView.as_view(), name="branch_material"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from userlogin import views as user_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("notes/", include('notes.urls')),
    path("register/",
         user_view.register, name="register"),
    path("profile/", user_view.profile, name="profile"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="userlogin/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="userlogin/logout.html"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="userlogin/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="userlogin/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="userlogin/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="userlogin/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("admin/", admin.site.urls),
    path(
        'password-change/',
        auth_views.PasswordChangeView.as_view(
            template_name='userlogin/password_change.html'),name="password_change",
    ),
    path(
        'password-change-done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='userlogin/password_change_done.html'), name="password_change_done",
    ),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.core.files import File

from pygments import highlight  # new
from pygments.formatters.html import HtmlFormatter  # new
from pygments.lexers import  guess_lexer  # new
from pygments.styles import get_all_styles


STYLE_CHOICES = sorted((item, item) for item in get_all_styles())
# Create your models here.
SEMESTER = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
)
STREAM = (
    ('CSE', 'CSE'),
    ('ECE', 'ECE'),
    ('EEE', 'EEE'),
    ('MECH', 'MECH'),
    ('CV', 'CV'),
    ('BCA', 'BCA'),
    ('BBA', 'BBA'),
    ('MCA', 'MCA'),
    ('MBA', 'MBA'),
    ('LLB', 'LLB'),
    ('LLM', 'LLM'),
    ('B-ARCH', 'B-ARCH'),
    ('BBA-HEM', 'BBA-HEM'),
    ('B-DES', 'B-DES'),
)
CHOICES = (
    ('plaintext', 'plaintext'),
    ('language-c', 'C'),
    ('language-csharp', 'C#'),
    ('language-cpp', 'C++'),
    ('language-python', 'Python'),
    ('language-java', 'Java'),
    ('language-javascript', 'JavaScript'),
    ('language-kotlin', 'Kotlin'),
    ('language-html,', 'HTML,'),
    ('language-css', 'CSS'),
    ('language-php7', 'PHP7'),
    ('language-arm', 'ARM'),
    ('language-xml', 'XML'),
    ('language-makefile', 'Makefile'),
    ('language-objective-c', 'Objective-C'),
    ('language-sql', 'SQL'),
    ('language-perl', 'Perl'),
    ('language-shell', 'Shell'),
    ('language-apache', 'Apache'),
    ('language-bash', 'Bash'),
    ('language-coffeescript', 'CoffeeScript'),
    ('language-diff', 'Diff'),
    ('language-go', 'Go'),
    ('language-http', 'HTTP'),
    ('language-json', 'JSON'),
    ('language-lesslua', 'LessLua'),
    ('language-markdown', 'Markdown'),
    ('language-ruby', 'Ruby'),
    ('language-rust', 'Rust'),
    ('language-scss', 'SCSS'),
    ('language-swift', 'Swift'),
    ('language-ini', 'INI'),
    ('language-typescript', 'TypeScript'),
    ('language-yaml', 'YAML'),
)


class LabPost(models.Model):

    title = models.CharField(max_length=100)
    subject = models.CharField(default="abcd", max_length=100)
    file = models.FileField(null=True, upload_to='files/', blank=True)

    stream = models.CharField(
        default='CSE', max_length=30, choices=STREAM)

    semester = models.IntegerField(default=1, choices=SEMESTER)

    description = models.TextField(blank=True, max_length=200)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    postbody = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    highlighted = models.TextField()  # new
    style = models.CharField(choices=STYLE_CHOICES,
                             default='perldoc', max_length=100)

    def save(self, *args, **kwargs):  # new
        """
        Use the `pygments` library to create a highlighted HTML
        representation of the code snippet.
        """
        lexer = guess_lexer(self.postbody)

        # linenos = 'table' if self.linenos else False
        linenos = 'table'
        formatter = HtmlFormatter(style=self.style,
                                  full=True)
        self.highlighted = highlight(self.postbody, lexer, formatter)
        super(LabPost, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('full_post', kwargs={'pk': self.pk})


class FilePost(models.Model):
    title = models.CharField(max_length=100)
    subject = models.CharField(default="", max_length=100)
    file0 = models.FileField(null=True, upload_to='filepost/', blank=True)
    file1 = models.FileField(null=True, upload_to='filepost/', blank=True)
    file2 = models.FileField(null=True, upload_to='filepost/', blank=True)
    file3 = models.FileField(null=True, upload_to='filepost/', blank=True)
    file4 = models.FileField(null=True, upload_to='filepost/', blank=True)
    file5 = models.FileField(null=True, upload_to='filepost/', blank=True)
    file6 = models.FileField(null=True, upload_to='filepost/', blank=True)

    stream = models.CharField(
        default='CSE', max_length=30, choices=STREAM)

    semester = models.IntegerField(default=1, choices=SEMESTER)
    list = ['filepost.file0', 'filepost.file1',
            'filepost.file2', 'filepost.file3'
            'filepost.file4', 'filepost.file5', 'filepost.file6'
            ]

    description = models.TextField(blank=True, max_length=200)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    language = models.CharField(
        default='plaintext', max_length=30, choices=CHOICES)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('material', kwargs={'pk': self.pk})

notes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import LabPost, FilePost
import os
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

# Create your views here.


class Posts(ListView):
    model = LabPost
    template_name = 'notes/index.html'
    # template_name = 'notes/index.html'
    context_object_name = 'labpost'
    ordering = ["-date_posted"]

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['filepost'] = FilePost.objects.all().order_by('-date_posted')
        # context['labpost']=LabPost.objects.all()
        return context





def about(request):
    return render(request, "notes/about.html")




#Post detail views
class fullpost(DetailView):
    model = LabPost


class filefullpost(DetailView):
    model = FilePost




#New Post views

class PostCreateView(LoginRequiredMixin, CreateView):  # LoginRequiredMixin,
    model = LabPost
    fields = [

        "title",
        "description",
        "semester",
        "stream",
        "subject",
        "file",
        "postbody",

    ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)





class FilePostCreateView(LoginRequiredMixin, CreateView):  # LoginRequiredMixin,
    model = FilePost
    fields = [

        "title",
        "description",
        "semester",
        "stream",
        "subject",
        "file0",
        "file1",
        "file2",
        "file3",
        "file4",
        "file5",
        "file6",


    ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)




#List Views
class labpostlistview(ListView):
    model = LabPost
    template_name = 'notes/labpost_all.html'
    context_object_name = 'posts'
    ordering = ["-date_posted"]
    paginate_by = 6


class materiallistview(ListView):
    model = FilePost
    template_name = 'notes/filepost_all.html'
    context_object_name = 'filepost'
    ordering = ["-date_posted"]
    paginate_by = 6


class UserPostListView(ListView):
    model = LabPost
    template_name = "notes/user_posts.html"  # app/model_viewtype.html
    context_object_name = "posts"
    # ordering = ["-date_posted"]

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return LabPost.objects.filter(author=user).order_by('-date_posted')







#Post update Views
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = LabPost
    fields = [
        "title",
        "description",
        "semester",
        "stream",
        "subject",
        "file",
        "postbody",
    ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


# LoginRequiredMixin,
class FilePostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = FilePost
    fields = [

        "title",
        "description",
        "semester",
        "stream",
        "subject",
        "file0",
        "file1",
        "file2",
        "file3",
        "file4",
        "file5",
        "file6",


    ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False



# Post Delete Views

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = LabPost
    success_url = "/notes"

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class FilePostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = FilePost
    success_url = "/notes"

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False





# category Filters

class SemesterLabListView(ListView):
    model = LabPost
    template_name = "notes/filter.html"  # app/model_viewtype.html
    context_object_name = "posts"
    # ordering = ["-date_posted"]

    def get_queryset(self):

        return LabPost.objects.filter(semester=self.kwargs.get('semester')).order_by('-date_posted')


class BranchLabListView(ListView):
    model = LabPost
    template_name = "notes/filter.html"  # app/model_viewtype.html
    context_object_name = "posts"
    # ordering = ["-date_posted"]

    def get_queryset(self):

        return LabPost.objects.filter(stream=self.kwargs.get('branch').upper()).order_by('-date_posted')


class SemesterMaterialListView(ListView):
    model = FilePost
    template_name = "notes/filter.html"  # app/model_viewtype.html
    context_object_name = "posts"
    # ordering = ["-date_posted"]

    def get_queryset(self):

        return FilePost.objects.filter(semester=self.kwargs.get('semester')).order_by('-date_posted')


class BranchMaterialListView(ListView):
    model = FilePost
    template_name = "notes/filter.html"  # app/model_viewtype.html
    context_object_name = "posts"
    # ordering = ["-date_posted"]

    def get_queryset(self):

        return FilePost.objects.filter(stream=self.kwargs.get('branch').upper()).order_by('-date_posted')

notes/templates/notes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Projekt</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/styles/default.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
    <link rel="stylesheet" href="{% static 'styles/default.css' %}">

<body>

    <!--Main Navigation-->
    <header>

        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
            <div class="container">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="{% url 'index' %}">
                    <strong class="blue-text">Home</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href={% url 'materials' %}>Material</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect"
                                href="{% url 'labposts' %}">Lab</a>
                        </li>
                    </ul>

                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'newpost' %}" data-toggle="tooltip" title="New Post"
                                class="nav-link  rounded waves-effect">
                                <i class="fa fa-pen"></i>
                            </a>
                        </li>
                        
                        <li class="nav-item">
                            <a href="{% url 'materialpost' %}" data-toggle="tooltip" title="Upload Material"
                                class="nav-link waves-effect">
                                <i class="fa fa-upload"></i>
                            </a>
                        </li>
                        
                        <li class="nav-item">
                            <a href="{% url 'profile' %}" data-toggle="tooltip" title="Edit Profile"
                                class="nav-link waves-effect">
                                <i class="fas fa-user-edit"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'logout' %}" data-toggle="tooltip" title="Log Out"
                                class="nav-link waves-effect">
                                <i class="fas fa-sign-out-alt"></i>
                            </a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{%url 'login'%}"
                            class="nav-link border border-light rounded waves-effect"
                            >
                            <i class="fas fa-user"></i>Login
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'register'%}"
                            class="nav-link border border-light rounded waves-effect ml-2"
                            >
                            <i class="fas fa-user-plus"></i>Sign Up
                            </a>
                        </li>
                        {% endif %}
                    </ul>

                </div>

            </div>
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main class="mt-5 pt-5">
        
        <div class="container">
            <!--Section: Jumbotron-->
            <section class="card wow fadeIn"
                style="background-image: url(https://mdbootstrap.com/img/Photos/Others/gradient1.jpg);">

                <!-- Content -->
                <div class="card-body text-white text-center px-5 ">

                    <h1 class="mb-1">
                        <strong>Welcome!</strong>
                    </h1>
                    <p class="mb-1">
                        <strong>Keep Sharing !!</strong>
                    </p>

                </div>
                <!-- Content -->
            </section>
            <!--Section: Jumbotron-->

            

<br>





            {% block content %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
            {{ message }}</div>
            {% endfor %}
            {% endif %}

            {% endblock %}

        </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer class="page-footer text-center  font-small mdb-color darken-2 mt-4 wow fadeIn">

        <!--Call to action-->
        <div class="pt-4">
            
        </div>
        <!--/.Call to action-->

        <hr class="my-2">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="https:/instagram.com/thewanixarif">
                <i class="fab fa-instagram mr-3"></i>
            </a>

            <!-- <a href="https://twitter.com/MDBootstrap">
                <i class="fab fa-twitter mr-3"></i>
            </a> -->

            <a href="https://www.youtube.com/channel/UCPtZqVRW1ZzesYwPoJtDJvQ">
                <i class="fab fa-youtube mr-3"></i>
            </a>


            <a href="https://github.com/wanixarif">
                <i class="fab fa-github mr-3"></i>
            </a>
        </div>
        <!-- Social icons -->

        <!--Copyright-->
        <div class="footer-copyright py-3">
           
           © <a href="htp://github.com/wanixarif"> Alphasoft</a>
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
        $(function () {
        $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>

</html>

notes/templates/notes/filepost_confirm_delete.html
{% extends "notes/base.html" %}
{% block content %}
<section class="text-center">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <section class="jumbotron text-center">
            <div class="container">
                <h4 class="jumbotron-heading">About to delete this post</h4>
                <p>
                    Are you sure?
                </p>
                <p>
                    <button class="btn btn-danger" type="submit">Yes</button>
                    <a class="btn btn-primary" href="{% url 'material' object.id %}">Cancel</a>
                </p>

            </div>
        </section>
    </form>
</section>
{% endblock content %}

notes/templates/notes/filepost_form.html
 {% extends "notes/base.html" %}
 {% load static %}
 {% load crispy_forms_tags %}
 <!--Main Navigation-->
 {% block content %}

 <style>
     .hide {
         display: none;
     }
 </style>
 <!--Section: Post-->
 <section class="mt">


     <div class="container">

         <!-- Grid column -->
         <div class="  col-lg-12 col-md-12">



             <!--Card content-->
             <div class="card-body ">
                 <form class="border border-light p-5" enctype="multipart/form-data" method="POST">
                     {% csrf_token %}
                     {{form|crispy}}
                     <div class="rounded" style="width:100%;height:20px;">
                         <div class="rounded text-center" id="bar"
                             style="color:white ;background-color : green;width:0px;height:20px;"> 100% Rendered</div>
                     </div>
                     <button class="btn btn-primary btn-rounded btn-block z-depth-0 my-4 waves-effect"
                         type="submit">POST</button>
                 </form>
             </div>


         </div>
         <!-- Grid column -->

     </div>

     <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
         integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>

     <script>
         $(document).ready(function () {
             $('#id_description').attr("rows", "2");
             $('label[for = "id_file0"]').html("File *");
             $('label[for = "id_file1"]').html("Add another file? ");
             $('label[for = "id_file2"]').html("Add another file? ");
             $('label[for = "id_file3"]').html("Add another file? ");
             $('label[for = "id_file4"]').html("Add another file? ");
             $('label[for = "id_file5"]').html("Add another file? ");
             $('label[for = "id_file6"]').html("Add another file? ");

             $('#div_id_file0').attr("class", "form-group show");
             $('#div_id_file1').attr("class", "form-group hide");
             $('#div_id_file2').attr("class", "form-group hide");
             $('#div_id_file3').attr("class", "form-group hide");
             $('#div_id_file4').attr("class", "form-group hide");
             $('#div_id_file5').attr("class", "form-group hide");
             $('#div_id_file6').attr("class", "form-group hide");


             //
             $('#div_id_file0').click(function () {

                 $('#div_id_file1').attr("class", "form-group");

             });

             $('#div_id_file1').click(function () {

                 $('#div_id_file2').attr("class", "form-group");

             });

             $('#div_id_file2').click(function () {

                 $('#div_id_file3').attr("class", "form-group");

             });
             $('#div_id_file3').click(function () {

                 $('#div_id_file4').attr("class", "form-group");

             });
             $('#div_id_file4').click(function () {

                 $('#div_id_file5').attr("class", "form-group");

             });
             $('#div_id_file5').click(function () {

                 $('#div_id_file5').attr("class", "form-group");
                 $("<div class='ml-auto mr-auto text-center'><a style = 'color:red;'>Maximum file limit reached, sorry can't add more files </a> </div>")
                     .insertAfter("#div_id_file5");

             });

         });
     </script>

 </section>


 {% endblock %}

notes/templates/notes/getrecentfilposts.html
<section class="text-center">

    <!--Grid row-->
    <div class="row mb-4 wow fadeIn">
        {% for post in posts.all|slice:":3"  %}
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

            <!--Card-->
            <div class="card">

                <!--Card image-->
                <div class="view overlay">
                    <img responsive
                        src="http://www.ultimateboardprep.com/wp-content/uploads/2015/05/icon_for_StudyMaterials.jpg"
                        class="card-img-top " alt="" style="height: 297px; margin-top: -12px; margin-bottom: -43px;">
                    <a href="{% url 'material' post.id %}">
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>

                <!--Card content-->
                <div class="card-body">
                    <!--Title-->
                    <h4 class="card-title">{{post.title}}</h4>
                    <!--Text-->
                    <p class="card-text">{{post.description}}</p>
                    <a href="" " class=" btn btn-primary btn-md">Free
                        download
                        <i class="fas fa-download ml-2"></i>
                    </a>
                </div>

            </div>
            <!--/.Card-->

        </div>
        <!--Grid column-->
        {% empty %}
        <p class="text-center font-bold">No posts yet<p>
                {% endfor %}


    </div>
</section>

notes/templates/notes/labpost_form.html
 {% extends "notes/base.html" %}
 {% load static %}
 {% load crispy_forms_tags %}
 <!--Main Navigation-->
 {% block content %}

 <!--Section: Post-->
 <section class="mt">


     <div class="container">

         <!-- Grid column -->
         <div class="  col-lg-12 col-md-12">



             <!--Card content-->
             <div class="card-body ">
                 <form class="border border-light p-5" enctype="multipart/form-data" method="POST">
                     {% csrf_token %}
                     {{form|crispy}}
                     <div class="rounded" style="width:100%;height:20px;">
                         <div class="rounded text-center"  id="bar"
                             style="color:white ;background-color : green;width:0px;height:20px;"> 100% Rendered</div>
                     </div>
                     <button class="btn btn-primary btn-rounded btn-block z-depth-0 my-4 waves-effect"
                         type="submit">POST</button>
                 </form>
             </div>


         </div>
         <!-- Grid column -->

     </div>

     <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
         integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>

     <script>
         $(document).ready(function () {
             $('#id_description').attr("rows", "2");
             $('#id_file').attr("onchange", "startRead()");
         });
     </script>

 </section>



 <script>
     function startRead() {
         // obtain input element through DOM 

         var file = document.getElementById('id_file').files[0];
         if (file) {
             getAsText(file);
         }
     }

     function getAsText(readFile) {
         var reader;
         try {
             reader = new FileReader();
         } catch (e) {
             document.getElementById('id_postbody').innerHTML =
                 "Error: seems File API is not supported on your browser";
             return;
         }

         // Read file into memory as UTF-8      
         reader.readAsText(readFile, "UTF-8");

         // Handle progress, success, and errors
         reader.onprogress = updateProgress;
         reader.onload = loaded;
         reader.onerror = errorHandler;
     }

     function updateProgress(evt) {
         if (evt.lengthComputable) {
             // evt.loaded and evt.total are ProgressEvent properties
             var loaded = (evt.loaded / evt.total);
             if (loaded < 1) {
                 // Increase the prog bar length
                 // style.width = (loaded * 200) + "px";
                 document.getElementById("bar").style.width = (loaded * 100) + "%";
             }
         }
     }

     function loaded(evt) {
         // Obtain the read file data    
         var fileString = evt.target.result;
         document.getElementById('id_postbody').innerHTML = fileString;
         document.getElementById("bar").style.width = 100 + "%";
     }

     function errorHandler(evt) {
         if (evt.target.error.code == evt.target.error.NOT_READABLE_ERR) {
             // The file could not be read
             document.getElementById('id_postbody').innerHTML = "Error reading file..."
         }
     }
 </script>




 {% endblock %}